# *File originally created by PDQTest*
# To run locally:
# https://confluence.atlassian.com/bitbucket/debug-your-pipelines-locally-with-docker-838273569.html
---
image: ruby:2.4.1

pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - ruby --version
          - bundler --version
          - wget https://apt.puppetlabs.com/puppet5-release-trusty.deb
          - dpkg -i puppet5-release-trusty.deb
          - apt-get update
          - apt install -y pdk
          - sh .ci_custom.sh
          - make pdqtestbundle
          - cd .pdqtest && bundle exec pdqtest --inplace --inplace-enable all

definitions:
  caches:
    bundler: vendor/bundle
